### PR TITLE
Switched to using classes

### LINKED ISSUE #30: Using Metrics and Standard logging
Hi, 

I'm trying to use this sdk for standard logging. `sumoLogger.log()` 
However, I also want to use it for metrics. `sumoLogger.log({path, value})`

enabling the `graphite: true` throws an **error** when trying to use it for standard logging. It looks like the path and value fields are mandatory as soon as you enable graphite.

```Sumo Logic requires both \'path\' and \'value\' properties to be provided in the message object```

Is there a way around this? 

Have multiple loggers (as shown below) does not seem to solve the issue either. 
```
 const logger1 = new SumoLogger(opts1)
 const logger2 = new SumoLogger(opts2)
```

### PR DESCRIPTION
**Pull request by clementallen**
Although classes were partly being used, there were some gaps which are now closed.  This also should partly fix #30 where config was being leaked between instances.  Now when two instances are created with different config they will behave separately

### CODE REVIEW

**Comment by clementallen** [comment]
@billsaysthis are you able to take a look at this please?  Would be good to help partially solve #30

**Comment by billsaysthis** [comment]
Thanks @clementallen once again, excellent.

**Comment by billsaysthis** [comment]
@clementallen does this require any changes to README?

**Comment by clementallen** [comment]
@billsaysthis it's all functional changes and the behaviour is exactly the same so no readme changes needed

**Pull request merged**
